name:                main
dependencies:
    - base
    - bytestring
    - file-embed

executables:
  mainexec:
    main:            Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
